### ISSUE TITLE
Password in multiple scripts

### ISSUE THREAD

**Issue by jamessewell** [starkandwayne/habitat-plans#17]
`PGPASSWORD={{cfg.superuser.password}}` appears in multiple scripts - best practice is to put this information in a` .pgpass `file rather than in scripts / env variables.

**Comment by jamessewell** [comment]
Also in recovery.conf:

`primary_conninfo = 'user={{cfg.replication.name}} password={{cfg.replication.password}} host={{svc.leader.sys.ip}} port={{cfg.port}} sslmode=prefer sslcompression=1'
`

**Comment by bodymindarts** [comment]
I've tried many ways of using a pgpass file but pg_basebackup and the replication settings don't seem to be picking it up.

I cannot figure out why.

**Comment by bodymindarts** [comment]
done!
